app_instance:
    run_report_dir: ./runreport_files
    plots: [
        Coverage (collapsed), On Target Percentage, Map Percent, PF Reads, Reads/SP, Insert Mean,
        Insert Stddev, R1 Mismatch Percent, R2 Mismatch Percent, R1 Indel Percent, R2 Indel Percent,
        R1 Soft Clip Percent, R2 Soft Clip Percent, R1 Length, R2 Length, Percent Mapped on Target,
        Estimated Yield (collapsed), PF Yield, Target Size (bp), Number of Targets
    ]
    port: 11038
    column_naming: ./config/column_naming.csv
    info_column: [Library, Barcode, Lane, Run Name, Study, Group ID, External Name, Target File, plotly_library_selected, plotly_unique_key]
default:
    plots: [Coverage (collapsed), On Target Percentage, Map Percent, PF Reads, Reads/SP, Insert Mean]
    order:
        plot: Coverage (collapsed)
        reverse: true
